# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(null=True)),
                ('parentesco', models.CharField(max_length=250, null=True)),
                ('nombres', models.CharField(max_length=250, null=True)),
                ('apellidos', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, null=True)),
                ('nombres', models.CharField(max_length=250, null=True)),
                ('apellidos', models.CharField(max_length=250, null=True)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('sexo', models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('convencional', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('direccion', models.CharField(max_length=300)),
                ('ocupacion', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
                ('idioma', models.SmallIntegerField(choices=[(0, 'Espanol'), (1, 'Ingles'), (2, 'Esp-Ing')], null=True)),
                ('estado', models.SmallIntegerField(choices=[(0, 'Activo'), (1, 'Inactivo'), (2, 'Pasante')], default=1)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('referencia', models.ManyToManyField(to='voluntariado.Referencia')),
            ],
        ),
    ]
